---
- name: CAS2 evm003 deploy 
  hosts: all
  gather_facts: no
  tasks:
  - name: DISPLAY THE INJECTED EXTRA VAR
    debug:
      # var: repo_login
      msg: repo_login {{ repo_login }}, repo_psw {{ repo_psw }}

  - name: CAS2 pull
    git:
      repo: https://{{repo_login}}:{{repo_psw}}@emaxsrl.git.beanstalkapp.com/cas2.git
      dest: /data/volumes/cas2
    # sudo_user: <your user that has the ssh key>
    # become: true
    # --ask-become-pass


    # - name: Update software repors
    #   command: apt upgrade
    #   become: yes
    #   become_user: root
    #   become_method: sudo
      #  --extra-vars='ansible_become_pass=password'