---
- name: CAS2 deploy@evm003
  hosts: all
  gather_facts: no
  tasks:
  # - name: DISPLAY THE INJECTED EXTRA VAR
  #   debug:
  #     msg: repo_login {{ repo_login | urlencode }}, repo_psw {{ repo_psw | urlencode  }}

  # - name: pull changes
  #   shell: chdir=/data/volumes/cas2 git pull https://{{ repo_login | urlencode }}:{{ repo_psw | urlencode }}@emaxsrl.git.beanstalkapp.com/cas2.git stage

  # - name: Go to CAS2 dir
  #   shell: chdir=/data/volumes/cas2

  - name: Git pull CAS2
    expect:
      chdir: /data/volumes/cas2
      command: git pull
      responses:
        Username: "{{ repo_login }}" # Username is a regex
        Password: "{{ repo_psw }}" # Password is a regex  
    # no_log: true

  - name: Build back-end
    command: yarn build
    args:
      chdir: /data/volumes/cas2/server

  - name: Build front-end
    command: yarn build
    args:
      chdir: /data/volumes/cas2/client

  - name: Restart docker image
    command: docker restart cas2
                

  # - name: CAS2 pull
  #   git:
  #     repo: https://{{ repo_login | urlencode }}:{{ repo_psw | urlencode }}@emaxsrl.git.beanstalkapp.com/cas2.git
  #     dest: /data/volumes/cas2
  #     update: yes
  #     accept_hostkey: yes
  #     clone: no
  #     force: yes
  #     remote: origin
  #     version: stage #branch 
    # sudo_user: <your user that has the ssh key>
    # become: true
    # --ask-become-pass


    # - name: Update software repors
    #   command: apt upgrade
    #   become: yes
    #   become_user: root
    #   become_method: sudo
      #  --extra-vars='ansible_become_pass=password'